CREATE TABLE KREW_STUCK_DOC_INCIDENT_T
(
      STUCK_DOC_INCIDENT_ID VARCHAR(40) NOT NULL,
      DOC_HDR_ID VARCHAR(40) NOT NULL,
      START_DT DATETIME NOT NULL,
      END_DT DATETIME,
      STATUS VARCHAR(20) NOT NULL,
      CONSTRAINT KREW_STUCK_DOC_INCIDENT_TP1 PRIMARY KEY(STUCK_DOC_INCIDENT_ID),
      CONSTRAINT KREW_STUCK_DOC_INCIDENT_TR1 FOREIGN KEY (DOC_HDR_ID) REFERENCES KREW_DOC_HDR_T(DOC_HDR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
/

CREATE TABLE KREW_STUCK_DOC_INCIDENT_S
(
	id bigint(19) not null auto_increment, primary key (id)
) ENGINE MyISAM
/
ALTER TABLE KREW_STUCK_DOC_INCIDENT_S auto_increment = 1000
/

CREATE TABLE KREW_STUCK_DOC_FIX_ATTMPT_T
(
      STUCK_DOC_FIX_ATTMPT_ID VARCHAR(40) NOT NULL,
      STUCK_DOC_INCIDENT_ID VARCHAR(40) NOT NULL,
      TIMESTAMP DATETIME NOT NULL,
      CONSTRAINT KREW_STUCK_DOC_AUDIT_TP1 PRIMARY KEY(STUCK_DOC_FIX_ATTMPT_ID),
      CONSTRAINT KREW_STUCK_DOC_AUDIT_TR1 FOREIGN KEY (STUCK_DOC_INCIDENT_ID) REFERENCES KREW_STUCK_DOC_INCIDENT_T(STUCK_DOC_INCIDENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
/

CREATE TABLE KREW_STUCK_DOC_FIX_ATTMPT_S
(
	id bigint(19) not null auto_increment, primary key (id)
) ENGINE MyISAM
/
ALTER TABLE KREW_STUCK_DOC_FIX_ATTMPT_S auto_increment = 1000
/
